name = "saas-stack-dev"
compatibility_date = "2025-03-25"
compatibility_flags = [ "nodejs_compat" ]
main = ".open-next/worker.js"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "saas-stack-db-dev"
database_id = "19b0ccd1-148d-48cc-adc3-8b5e3f23d1b5"
migrations_dir = "./drizzle"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "saas-stack-bucket-dev"
